<?php

namespace common\models;

use Yii;
use yii\alexposseda\fileManager\FileManager;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Expression;

/**
 * This is the model class for table "{{%news}}".
 *
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property integer $active
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $photo
 *
 * @property mixed          logo
 */
class NewsModel extends ActiveRecord
{
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),

        ];
    }
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%news}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['description', 'photo'], 'string'],
            [['active', 'created_at', 'updated_at'], 'integer'],
            [['title'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'description' => 'Description',
            'active' => 'Active',
            'created_at' => 'Create At',
            'updated_at' => 'Update At',
            'photo' => 'Photo',
        ];
    }

    public function getLogo(){
        if(!empty($this->photo)){
            return FileManager::getInstance()
                              ->getStorageUrl().json_decode($this->photo)[0];
        }

        return null;
    }

    public function beforeDelete(){

        if(!empty($this->photo)){
            FileManager::getInstance()
                       ->removeFile(json_decode($this->photo)[0]);
        }

        return true;
    }

    public function afterSave($insert, $changedAttributes){
        FileManager::getInstance()->removeFromSession(json_decode($this->photo)[0]);
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

    }

}
